!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'train',
        one_hot: 1,
        center: 1,
        preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
            items: [ 
                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                   ]
        }
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 128,
        layers: [
                !obj:pylearn2.models.powerup.Powerup {
                     layer_name: 'h0',
                     num_units: %(powerup_nunits)i,
                     num_pieces: %(powerup_npieces)i,
                     post_bias: True,
                     p_mean: 1.0,
                     W_lr_scale: %(W_lr_scale)f,
                     p_lr_scale: %(p_lr_scale)f,
                     max_col_norm: %(max_col_norm)f,
                     batch_size: 128,
                     irange: .005,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: %(max_col_norm2)f,
                     layer_name: 'y',
                     n_classes: 7,
                     irange: .005
                 }
                ],
        nvis: 2304
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: %(lr_rate)f,
        init_momentum: %(init_mom)f,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'valid',
                              one_hot: 1,
                              center: 1,
                              preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
                                  items: [
                                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                                   ]
                              }
                          },
                'test' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'test',
                              one_hot: 1,
                              center: 1,
                              preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
                                  items: [
                                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                                   ]
                              }
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { 
            costs: [
                !obj:pylearn2.costs.cost.MethodCost {
                    method: 'cost_from_X'
                },
                !obj:pylearn2.models.mlp.WeightDecay {
                    coeffs: [ %(l2_pen)f, %(l2_pen2)f ]
                }
            ],
        },
       termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)sbest.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: %(final_mom)f
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 250,
            decay_factor: %(decay_factor)f
        }
    ],
    save_path: "%(save_path)slast.pkl",
    save_freq: 5
}
