!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.tfd.TFD {
        which_set: 'train',
        one_hot: 1,
        center: 1,
        preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
            items: [ 
                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                   ]
        }
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.powerup.Powerup {
                     layer_name: 'h0',
                     num_units: 300,
                     p_mean: 1.0,
                     post_bias: True,
                     normalize: True,
                     max_col_norm: 1.9365,
                     batch_size: 256,
                     num_pieces: 4,
                     irange: .005
                 },
                 !obj:pylearn2.models.powerup.Powerup {
                     layer_name: 'h1',
                     num_units: 300,
                     p_mean: 1.0,
                     post_bias: True,
                     normalize: True,
                     max_col_norm: 1.9365,
                     batch_size: 256,
                     num_pieces: 4,
                     irange: .005
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 7,
                     irange: .005
                 }
            ],
        nvis: 2304,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 256,
        learning_rate: 0.12,
        init_momentum: 0.5,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'valid',
                              one_hot: 1,
                              center: 1,
                              preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
                                  items: [
                                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                                   ]
                              }
                          },
                'test' : !obj:pylearn2.datasets.tfd.TFD {
                              which_set: 'test',
                              one_hot: 1,
                              center: 1,
                              preprocessor: !obj:pylearn2.datasets.preprocessing.Pipeline {
                                  items: [
                                       !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                                   ]
                              }
                          }
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
                    input_include_probs: { 'h0' : .5, 'h1': .5 },
                    input_scales: { 'h0': 2. , 'h1': 2.}
             },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
         },
        },
        #!obj:pylearn2.costs.cost.SumOfCosts {
            #costs: [
                   #!obj:pylearn2.costs.cost.MethodCost {
                   #     method: 'cost_from_X',
                   #     supervised: 1
                   # },
                   # !obj:pylearn2.costs.mlp.WeightDecay {
                   #     coeffs: [.00009, .00009, .00004]
                   #},
                #],
        #},
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "tfd_mlp_tmp_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: 0.6
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 250,
            decay_factor: 0.01
        }
    ],
    save_path: "%(save_path)slast.pkl",
    save_freq: 5
}
