#!/bin/bash -l
# Bash is needed because we use its "array" data structure
# the -l flag means it will act like a login shell,
# and source the .profile, .bashrc, and so on

# List of all tasks to execute
tasks=(
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
'jobman sql postgresql://gulcehrc@opter.iro.umontreal.ca/gulcehrc_db?table=powerup_tfd_1layer_finer .'
)

# Execute the task
${tasks[$PBS_ARRAYID]}
